version: '3'

services:
  app:
    image: stivenramireza/nodejsapp:1.0
    ports:
      - "3000:3000"
    volumes:
      - myfirstvolume:/usr/src/app

    restart: always
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"

volumes:
  myfirstvolume: